import os
import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
import docx

def generate_pdf_report(scan, fields, violations, image_path: str) -> str:
    filename = f"report_{scan.id}.pdf"
    filepath = os.path.join("reports", filename)
    
    doc = SimpleDocTemplate(filepath, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    story.append(Paragraph(f"MetroVigil Statutory Compliance Report - Scan #{scan.id}", styles['Title']))

    story.append(Paragraph("Legal Metrology (Packaged Commodities) Rules, 2011", styles['Heading3']))
    story.append(Spacer(1, 10))

    
    # Status
    status_text = f"Compliance Status: {scan.compliance_status.upper() if scan.compliance_status else 'UNKNOWN'}"
    story.append(Paragraph(status_text, styles['Heading2']))
    story.append(Paragraph(f"Score: {scan.compliance_score if scan.compliance_score else 'N/A'}/100", styles['Normal']))
    story.append(Spacer(1, 12))
    
    if os.path.exists(image_path):
        try:
            img = RLImage(image_path, width=200, height=200)
            story.append(img)
            story.append(Spacer(1, 12))
        except Exception as e:
            print(f"Error adding image to PDF: {e}")

    story.append(Paragraph("Extracted Fields", styles['Heading2']))
    field_data = [["Field Name", "Value", "Present", "Rule"]]
    for f in fields:
        field_data.append([f.field_name, str(f.field_value) if f.field_value else "N/A", "Yes" if f.is_present else "No", str(f.rule_reference)])
    
    ft = Table(field_data)
    ft.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.grey),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('GRID', (0,0), (-1,-1), 1, colors.black)
    ]))
    story.append(ft)
    story.append(Spacer(1, 12))
    
    story.append(Paragraph("Violations", styles['Heading2']))
    if violations:
        vio_data = [["Rule", "Description", "Severity", "Details", "Suggestion"]]
        for v in violations:
            vio_data.append([v.rule_number, v.rule_description, v.severity, v.details, v.suggestion])
        vt = Table(vio_data)
        vt.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.grey),
            ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('GRID', (0,0), (-1,-1), 1, colors.black)
        ]))
        story.append(vt)
    else:
        story.append(Paragraph("No violations found.", styles['Normal']))
    
    story.append(Spacer(1, 24))
    story.append(Paragraph(f"Generated by MetroVigil (AI-Powered Legal Metrology Compliance Engine) on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
    
    doc.build(story)
    return filepath

def generate_docx_report(scan, fields, violations, image_path: str) -> str:
    filename = f"report_{scan.id}.docx"
    filepath = os.path.join("reports", filename)
    
    doc = docx.Document()
    doc.add_heading(f"MetroVigil Statutory Compliance Report - Scan #{scan.id}", 0)

    
    doc.add_heading("Summary", level=1)
    doc.add_paragraph(f"Compliance Status: {scan.compliance_status.upper() if scan.compliance_status else 'UNKNOWN'}")
    doc.add_paragraph(f"Score: {scan.compliance_score if scan.compliance_score else 'N/A'}/100")
    
    if os.path.exists(image_path):
        try:
            doc.add_picture(image_path, width=docx.shared.Inches(3))
        except Exception:
            pass
            
    doc.add_heading("Extracted Fields", level=1)
    table = doc.add_table(rows=1, cols=4)
    table.style = 'Table Grid'
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Field Name'
    hdr_cells[1].text = 'Value'
    hdr_cells[2].text = 'Present'
    hdr_cells[3].text = 'Rule'
    
    for f in fields:
        row_cells = table.add_row().cells
        row_cells[0].text = f.field_name
        row_cells[1].text = str(f.field_value) if f.field_value else "N/A"
        row_cells[2].text = "Yes" if f.is_present else "No"
        row_cells[3].text = str(f.rule_reference)
        
    doc.add_heading("Violations", level=1)
    if violations:
        vtable = doc.add_table(rows=1, cols=5)
        vtable.style = 'Table Grid'
        hdr_cells = vtable.rows[0].cells
        hdr_cells[0].text = 'Rule'
        hdr_cells[1].text = 'Description'
        hdr_cells[2].text = 'Severity'
        hdr_cells[3].text = 'Details'
        hdr_cells[4].text = 'Suggestion'
        
        for v in violations:
            row_cells = vtable.add_row().cells
            row_cells[0].text = v.rule_number
            row_cells[1].text = v.rule_description
            row_cells[2].text = v.severity
            row_cells[3].text = v.details
            row_cells[4].text = v.suggestion
    else:
        doc.add_paragraph("No violations found.")
    doc.add_paragraph(f"\nGenerated by MetroVigil (AI-Powered Legal Metrology Compliance Engine) on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    
    doc.save(filepath)
    return filepath

